"""add User email index & token_version field

Revision ID: 176cfe52af86
Revises: 7ea6bfab313a
Create Date: 2025-11-04 11:30:56.780136

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '176cfe52af86'
down_revision: Union[str, Sequence[str], None] = '7ea6bfab313a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('app_user', sa.Column('token_version', sa.Integer(), nullable=False, server_default='0'))
    op.create_index(op.f('ix_app_user_email'), 'app_user', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_app_user_email'), table_name='app_user')
    op.drop_column('app_user', 'token_version')
    # ### end Alembic commands ###
