"""add_consent_status_to_user_consent_audit

Revision ID: 1e224c0fa607
Revises: ae18864dab98
Create Date: 2026-01-22 00:56:03.184031

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1e224c0fa607'
down_revision: Union[str, Sequence[str], None] = 'ae18864dab98'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    consent_status_enum = sa.Enum('GRANTED', 'REVOKED', name='consent_status_enum')
    consent_status_enum.create(op.get_bind())
    op.add_column('user_consent_audit', sa.Column('consent_status', consent_status_enum, server_default='GRANTED', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_consent_audit', 'consent_status')
    consent_status_enum = sa.Enum('GRANTED', 'REVOKED', name='consent_status_enum')
    consent_status_enum.drop(op.get_bind())
    # ### end Alembic commands ###
