"""add scheduled transaction table

Revision ID: aac479163022
Revises: f05b8becf1e5
Create Date: 2026-01-21 13:12:56.260842

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'aac479163022'
down_revision: Union[str, Sequence[str], None] = 'f05b8becf1e5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Handle existing enum modification first
    op.execute("ALTER TYPE transaction_status_enum ADD VALUE IF NOT EXISTS 'ACTIVE'")
    
    op.create_table(
        'scheduled_transaction',
        sa.Column('id', sa.Uuid(), nullable=False),
        sa.Column('user_id', sa.Uuid(), nullable=False),
        sa.Column('amount', sa.Numeric(precision=15, scale=4), nullable=False),

        sa.Column(
            'currency',
            postgresql.ENUM(
                'EUR', 'USD', 'PLN', 'GBP',
                name='currency_enum',
                create_type=False
            ),
            server_default='EUR',
            nullable=False
        ),

        sa.Column(
            'frequency',
            postgresql.ENUM(
                'ONCE', 'DAILY', 'WEEKLY', 'MONTHLY',
                name='transaction_frequency_enum',
                create_type=True
            ),
            nullable=False
        ),

        sa.Column('day_of_week', sa.Integer(), nullable=True),
        sa.Column('start_date', sa.DateTime(timezone=True), nullable=False),
        sa.Column('end_date', sa.DateTime(timezone=True), nullable=True),

        sa.Column(
            'destination_type',
            postgresql.ENUM(
                'GOAL', 'GROUP',
                name='destination_type_enum',
                create_type=True
            ),
            nullable=False
        ),

        sa.Column('goal_id', sa.Uuid(), nullable=True),
        sa.Column('group_id', sa.Uuid(), nullable=True),

        sa.Column(
            'status',
            postgresql.ENUM(
                'ACTIVE', 'PENDING', 'COMPLETED', 'FAILED',
                name='transaction_status_enum',
                create_type=False
            ),
            server_default='PENDING',
            nullable=False
        ),

        sa.Column('cron_expression', sa.String(), nullable=True),
        sa.Column('next_run_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('projection_log', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),

        sa.ForeignKeyConstraint(['group_id'], ['groups.id']),
        sa.ForeignKeyConstraint(['user_id'], ['app_user.id']),
        sa.PrimaryKeyConstraint('id'),
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('scheduled_transaction')
    op.execute("DROP TYPE IF EXISTS transaction_frequency_enum")
    op.execute("DROP TYPE IF EXISTS destination_type_enum")
    # ### end Alembic commands ###
