"""add user consent audit table

Revision ID: ae18864dab98
Revises: aac479163022
Create Date: 2026-01-21 23:02:08.310553

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ae18864dab98'
down_revision: Union[str, Sequence[str], None] = 'aac479163022'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_consent_audit',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('consent_type', sa.Enum('SAVEBUDDY_AI', name='consent_type_enum'), nullable=False),
    sa.Column('version', sa.String(), nullable=False),
    sa.Column('source_ip', sa.String(), nullable=False),
    sa.Column('user_agent', sa.String(), nullable=False),
    sa.Column('granted_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['app_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_consent_audit')
    # ### end Alembic commands ###
