"""auto-detect model changes

Revision ID: cc203c8e6123
Revises: 000000000002
Create Date: 2025-12-03 22:57:17.801572

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'cc203c8e6123'
down_revision: Union[str, Sequence[str], None] = '000000000002'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_app_user_created_at'), 'app_user', ['created_at'], unique=False)
    op.create_index(op.f('ix_gdpr_request_created_at'), 'gdpr_request', ['created_at'], unique=False)
    op.alter_column('group_member', 'role',
               existing_type=postgresql.ENUM('ADMIN', 'MEMBER', name='group_role_enum'),
               nullable=True,
               existing_server_default=sa.text("'MEMBER'::group_role_enum"))
    op.alter_column('group_member', 'contributed_amount',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=True,
               existing_server_default=sa.text("'0'::numeric"))
    op.alter_column('group_member', 'joined_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('group_transaction_message', 'type',
               existing_type=postgresql.ENUM('WALLET_DEPOSIT', 'WALLET_WITHDRAWAL', 'GROUP_SAVINGS_DEPOSIT', 'GROUP_SAVINGS_WITHDRAWAL', 'INDIVIDUAL_SAVINGS_DEPOSIT', 'INDIVIDUAL_SAVINGS_WITHDRAWAL', name='transaction_type_enum'),
               nullable=True,
               existing_server_default=sa.text("'GROUP_SAVINGS_DEPOSIT'::transaction_type_enum"))
    op.alter_column('group_transaction_message', 'timestamp',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('groups', 'current_balance',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=True,
               existing_server_default=sa.text("'0'::numeric"))
    op.alter_column('removed_group_member', 'removed_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('transaction', 'is_anonymized',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.create_index(op.f('ix_transaction_created_at'), 'transaction', ['created_at'], unique=False)
    op.alter_column('wallet', 'is_anonymized',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.create_index(op.f('ix_wallet_created_at'), 'wallet', ['created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_wallet_created_at'), table_name='wallet')
    op.alter_column('wallet', 'is_anonymized',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.drop_index(op.f('ix_transaction_created_at'), table_name='transaction')
    op.alter_column('transaction', 'is_anonymized',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('removed_group_member', 'removed_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('groups', 'current_balance',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=False,
               existing_server_default=sa.text("'0'::numeric"))
    op.alter_column('group_transaction_message', 'timestamp',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('group_transaction_message', 'type',
               existing_type=postgresql.ENUM('WALLET_DEPOSIT', 'WALLET_WITHDRAWAL', 'GROUP_SAVINGS_DEPOSIT', 'GROUP_SAVINGS_WITHDRAWAL', 'INDIVIDUAL_SAVINGS_DEPOSIT', 'INDIVIDUAL_SAVINGS_WITHDRAWAL', name='transaction_type_enum'),
               nullable=False,
               existing_server_default=sa.text("'GROUP_SAVINGS_DEPOSIT'::transaction_type_enum"))
    op.alter_column('group_member', 'joined_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('group_member', 'contributed_amount',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=False,
               existing_server_default=sa.text("'0'::numeric"))
    op.alter_column('group_member', 'role',
               existing_type=postgresql.ENUM('ADMIN', 'MEMBER', name='group_role_enum'),
               nullable=False,
               existing_server_default=sa.text("'MEMBER'::group_role_enum"))
    op.drop_index(op.f('ix_gdpr_request_created_at'), table_name='gdpr_request')
    op.drop_index(op.f('ix_app_user_created_at'), table_name='app_user')
    # ### end Alembic commands ###
