"""

Revision ID: f05b8becf1e5
Revises: cc203c8e6123
Create Date: 2026-01-12 19:24:37.574638

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f05b8becf1e5'
down_revision: Union[str, Sequence[str], None] = 'cc203c8e6123'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ims_action',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('user_prompt', sa.String(), nullable=False),
    sa.Column('intent', sa.String(), nullable=False),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['app_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('group_member', 'role',
               existing_type=postgresql.ENUM('ADMIN', 'MEMBER', name='group_role_enum'),
               nullable=True,
               existing_server_default=sa.text("'MEMBER'::group_role_enum"))
    op.alter_column('group_member', 'contributed_amount',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=True,
               existing_server_default=sa.text("'0'::numeric"))
    op.alter_column('group_member', 'joined_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('group_transaction_message', 'type',
               existing_type=postgresql.ENUM('WALLET_DEPOSIT', 'WALLET_WITHDRAWAL', 'GROUP_SAVINGS_DEPOSIT', 'GROUP_SAVINGS_WITHDRAWAL', 'INDIVIDUAL_SAVINGS_DEPOSIT', 'INDIVIDUAL_SAVINGS_WITHDRAWAL', name='transaction_type_enum'),
               nullable=True,
               existing_server_default=sa.text("'GROUP_SAVINGS_DEPOSIT'::transaction_type_enum"))
    op.alter_column('group_transaction_message', 'timestamp',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('groups', 'current_balance',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=True,
               existing_server_default=sa.text("'0'::numeric"))
    op.alter_column('removed_group_member', 'removed_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('transaction', 'is_anonymized',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('wallet', 'is_anonymized',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('wallet', 'is_anonymized',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('transaction', 'is_anonymized',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('removed_group_member', 'removed_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('groups', 'current_balance',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=False,
               existing_server_default=sa.text("'0'::numeric"))
    op.alter_column('group_transaction_message', 'timestamp',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('group_transaction_message', 'type',
               existing_type=postgresql.ENUM('WALLET_DEPOSIT', 'WALLET_WITHDRAWAL', 'GROUP_SAVINGS_DEPOSIT', 'GROUP_SAVINGS_WITHDRAWAL', 'INDIVIDUAL_SAVINGS_DEPOSIT', 'INDIVIDUAL_SAVINGS_WITHDRAWAL', name='transaction_type_enum'),
               nullable=False,
               existing_server_default=sa.text("'GROUP_SAVINGS_DEPOSIT'::transaction_type_enum"))
    op.alter_column('group_member', 'joined_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('group_member', 'contributed_amount',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=False,
               existing_server_default=sa.text("'0'::numeric"))
    op.alter_column('group_member', 'role',
               existing_type=postgresql.ENUM('ADMIN', 'MEMBER', name='group_role_enum'),
               nullable=False,
               existing_server_default=sa.text("'MEMBER'::group_role_enum"))
    op.drop_table('ims_action')
    # ### end Alembic commands ###
